apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres
  title: Postgres (Production)
  description: A Managed Postgres DB, hosted on DigitalOcean
  annotation:
    backstage.io/view-url: https://github.com/theaccordance/backstage/blob/main/backstage/resources/postgres-production.yaml
    backstage.io/edit-url: https://github.com/theaccordance/backstage/blob/main/backstage/resources/postgres-production.yaml
  tags:
    - sql
    - database
spec:
  type: database
  owner: engineering
  system: mainwaring-dev
