apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: balena-push
  description: A Github Action to continuously delivery your projects to balena.io
  title: Balena Push
  annotations:
    backstage.io/view-url: https://github.com/theaccordance/backstage/blob/main/backstage/libraries/balena-push.yaml
    backstage.io/edit-url: https://github.com/theaccordance/backstage/blob/main/backstage/libraries/balena-push.yaml
    backstage.io/source-location: url:https://github.com/theaccordance/balena-push/tree/master/
    github.com/project-slug: theaccordance/balena-push
  tags:
    - github-actions
  links:
    - url: https://github.com/marketplace/actions/balena-push
      title: Github Actions Marketplace Listing
      icon: storefront
    - url: https://www.github.com/theaccordance/balena-push
      title: Github
      icon: github
spec:
  type: library
  owner: joe@mainwaring.dev
  lifecycle: production
