# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "theaccordance"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "theaccordance"
    schedule:
      interval: "weekly"


