# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: knowhere-space
  title: Knowhere.space
  description:  A Personal Homelab I have exposed to the internet.
spec:
  owner: engineering
