# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  title: Guests
  description:  This group is intended for public access to demo purposes, in a real-world scenario I would be unlikely to include this group.
spec:
  type: team
  children: []
