apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chartbrew-server
  title: Chartbrew Server
  description:  Open-source web platform used to create live reporting dashboards from APIs, MongoDB, Firestore, MySQL, PostgreSQL, and more 📈📊
  annotations:
    backstage.io/view-url: https://github.com/theaccordance/backstage/blob/main/backstage/services/chartbrew.yaml
    backstage.io/edit-url: https://github.com/theaccordance/backstage/blob/main/backstage/services/chartbrew.yaml
  labels:
    mainwaring.dev/host: heroku.com
spec:
  type: service
  lifecycle: production
  owner: engineering
  system: mainwaring-dev
#  providesApis: [example-grpc-api]
