# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  title: Guest
  description:  Look, but don't touch!
  annotations:
    backstage.io/view-url: https://github.com/theaccordance/backstage/blob/main/backstage/users/guest.yaml
    backstage.io/edit-url: https://github.com/theaccordance/backstage/blob/main/backstage/users/guest.yaml
spec:
  memberOf: [engineering]
