apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chartbrew-frontend
  title: API
  description:  A Robust REST server using Strapi to expose data to other websites and resources.
spec:
  type: website
  lifecycle: production
  owner: engineering
  system: mainwaring-dev
#  providesApis: [example-grpc-api]
