apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chartbrew-app
  title: Chartbrew App
  description:  Open-source web platform used to create live reporting dashboards from APIs, MongoDB, Firestore, MySQL, PostgreSQL, and more 📈📊
  labels:
    mainwaring.dev/host: vercel.com
  links:
    - url: https://chartbrew.mainwaring.dev
      title: Application Website
      icon: public
spec:
  type: website
  lifecycle: production
  owner: engineering
  system: mainwaring-dev
#  providesApis: [example-grpc-api]
