# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  push:
    branches:
      - main
    paths:
      - 'backstage/**'
      - 'packages/backend/**'
      - 'plugins/**'
      - 'package.json'
  workflow_dispatch:
jobs:
  deploy:
    name: "Deploy Backstage.io Backend to Digital Ocean"
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}

